dataset:
  feature_key: feats
  folder: data/zenodo_data/fourvec
  label_key: label
  num_particles: 32
hyperparams:
  batch_size: 512
  epochs: 140
  patience: 140
  val_size: -1
  verbose: 1
  weight_decay: 0.0
model:
  input:
    data_format: pxpypze
    spurions: true
  lineq2v0:
    activation: null
    batchnorm: false
    dropout: 0.0
    n_outputs: 5
    num_particles_avg: 25
  lineq2v2:
    activation: relu
    batchnorm: false
    dropout: 0.0
    n_hidden: 2
    num_particles_avg: 25
save_dir:
  folder: zenodo-testing
  name: long
seed: 1812682482
