name: pelican
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - libexpat=2.6.2
  - libffi=3.4.2
  - libsqlite=3.45.3
  - libzlib=1.2.13
  - openssl=3.3.0
  - pip=24.0
  - python=3.12.3
  - setuptools=69.5.1
  - tk=8.6.13
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - pip:
    - absl-py=
    - astunparse=
    - certifi=
    - charset-normalizer=
    - colorama=
    - flatbuffers=
    - gast=
    - google-pasta=
    - grpcio=
    - h5py=
    - idna=
    - keras=
    - libclang=
    - markdown=
    - markdown-it-py=
    - markupsafe=
    - mdurl=
    - ml-dtypes=
    - namex=
    - numpy=
    - opt-einsum=
    - optree=
    - packaging=
    - protobuf=
    - pygments=
    - pyyaml=
    - requests=
    - rich=
    - six=
    - tensorboard=
    - tensorboard-data-server=
    - tensorflow=
    - tensorflow-intel=
    - termcolor=
    - tqdm=
    - typing-extensions=
    - urllib3=
    - werkzeug=
    - wrapt=
