dataset:
  folder: data/nano_data
  feature_key: Pmu
  label_key: is_signal
  num_particles: 34

save_dir:
  folder: experiments
  name: test

hyperparams:
  epochs: 140
  batch_size: 512
  verbose: 0

model:
  input:
    data_format: Epxpypz
    instantons: True

  lineq2v2:
    n_hidden: 1
    activation: relu
    dropout: 0.0
    batchnorm: True
    num_particles_avg: 25
  lineq2v0:
    n_outputs: 1
    activation: null
    dropout: 0.0
    batchnorm: True
    num_particles_avg: 25