
hyperparams:
  epochs: 20
  batch_size: 512


data_dir:
  folder: zenodo_data
  feature_key: jetConstituentList
  label_key: jets


model:
  input:
    data_format: inverted
    num_particles: 32

  nano2v2:
    bnorm: True
    activ: relu
    hidden: 3
    num_avg_part: 15

  nano2v0:
    bnorm: True
    activ: null
    outputs: 5
    num_avg_part: 15


