dataset:
  feature_key: Pmu
  folder: data/sample_data
  label_key: is_signal
  load: true
  num_particles: 32
hyperparams:
  batch_size: 512
  epochs: 20
  weight_decay: 0.005
model:
  input:
    data_format: Epxpypz
  lineq2v0:
    activation: null
    batchnorm: true
    dropout: 0.0
    n_outputs: 1
    num_particles_avg: 50
  lineq2v2:
    activation: relu
    batchnorm: true
    dropout: 0.0
    n_hidden: 1
    num_particles_avg: 50
save_dir:
  folder: yamltest
  name: test
