dataset:
  feature_key: Pmu
  folder: data/nano_data
  label_key: is_signal
  num_particles: 32
hyperparams:
  batch_size: 512
  epochs: 140
  patience: 20
  val_size: 50000
  weight_decay: 0.0
model:
  input:
    data_format: Epxpypz
  lineq2v0:
    activation: null
    batchnorm: true
    dropout: 0.0
    n_outputs: 1
    num_particles_avg: 25
  lineq2v2:
    activation: relu
    batchnorm: true
    dropout: 0.0
    n_hidden: 3
    num_particles_avg: 25
save_dir:
  folder: experiments
  name: long
seed: 1898749687
