dataset:
  feature_key: Pmu
  folder: data/osf_data
  label_key: jet_tag
  num_particles: 16
hyperparams:
  batch_size: 512
  epochs: 140
  patience: 140
  val_size: -1
  verbose: 1
  weight_decay: 0.0
model:
  input:
    data_format: epxpypz
    spurions: true
  lineq2v0:
    activation: null
    batchnorm: false
    dropout: 0.0
    n_outputs: 5
    num_particles_avg: 25
  lineq2v2:
    activation: relu
    batchnorm: false
    dropout: 0.0
    n_hidden: 1
    num_particles_avg: 25
save_dir:
  folder: bug-testing
  name: long
seed: 282337891
