dataset:
  folder: data/zenodo_data
  feature_key: feats
  label_key: label
  num_particles: 32

save_dir:
  folder: zenodo-testing
  name: long

hyperparams:
  epochs: 140
  batch_size: 512
  verbose: 1

model:
  input:
    data_format: pxpypze
    spurions: True

  lineq2v2:
    n_hidden: 5
    activation: relu
    dropout: 0.0
    batchnorm: False
    num_particles_avg: 25
  lineq2v0:
    n_outputs: 5
    activation: null
    dropout: 0.0
    batchnorm: False
    num_particles_avg: 25
seed: 1812682482
