#!/usr/bin/env python

import argparse

def load_arguments():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--dir", required=True,  type=str)
    parser.add_argument("--name",  type=str, default='')

    args = parser.parse_args()
    return args


def main():
    args = load_arguments()


if __name__ == '__main__':
    main()

