dataset:
  feature_key: feats
  folder: ../../../data/zenodo_data/fourvec
  label_key: label
  num_particles: 32
hyperparams:
  batch_size: 512
  epochs: 1000
  lr_init: 0.01
  patience: 4
  val_size: -1
  verbose: 1
model:
  batchnorm: false
  hidden:
    activs:
    - relu
    units:
    - 2
  inner_product:
    data_format: pxpypze
    spurions: false
  num_avg: 75
  order: 2
  out:
    activs:
    - softmax
    units:
    - 5
save_dir: nano-pelican
seed: 1366171783
